name 'blp-updatedb'
version '1.0.0'
maintainer 'Bloomberg Finance L.P.'
maintainer_email 'chef@bloomberg.net'
license 'Apache-2.0'
description 'Configures updatedb'
long_description 'Configures updatedb'

issues_url 'https://github.com/bloomberg-cookbooks/updatedb/issues'
source_url 'https://github.com/bloomberg-cookbooks/updatedb'
chef_version '>= 12.5'

supports 'centos', '>= 6.0'
supports 'redhat', '>= 6.0'
supports 'ubuntu', '>= 12.04'
